# Generated by Django 2.1.4 on 2018-12-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('pass1', models.CharField(max_length=20)),
                ('repass', models.CharField(max_length=20)),
            ],
        ),
    ]
